using Albatross.CommandLine;
using Albatross.Config;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using System.Threading.Tasks;

namespace AotTest {
	class Program {
		static async Task<int> Main(string[] args) {
			await using var host = new CommandHost("AOT Test Application")
				.RegisterServices(RegisterServices)
				.AddCommands()
				.Parse(args)
				.Build();
			return await host.InvokeAsync();
		}

		static void RegisterServices(ParseResult result, IServiceCollection services) {
			services.AddConfig<MyConfig>();
			// generated by the source generator
			services.RegisterCommands();
		}
	}
}
